name: Build

on:
  workflow_dispatch:
    inputs:
      rebuild:
        description: 'Rebuild but not release'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - userName: q215613905
            repoUrl: https://github.com/q215613905/TVBoxOS
            branchName: main
          - userName: takagen99
            repoUrl: https://github.com/takagen99/Box
            branchName: main
            javaVersion: 17

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: actions

      - name: Clone Source Code
        run: |
          git clone --depth=1 -b ${{ matrix.branchName }} ${{ matrix.repoUrl }} TVBoxOSC
          cd TVBoxOSC
          git fetch --unshallow

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.javaVersion || 11 }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build With Gradle
        working-directory: TVBoxOSC
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --build-cache --parallel --daemon --warning-mode all

      - name: Rename App
        working-directory: TVBoxOSC
        run: |
          rm -rf apk/
          mkdir -p apk/
          for file in `find . -name "*.apk" -print`; do
            filename=$(basename "$file")
            if [[ $filename =~ "release" ]] ; then
              new_name="TVBox_${{ matrix.userName }}.apk"
              mv "$file" "apk/$new_name"
            fi
          done

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TVBox_APK
          path: TVBoxOSC/apk/*.apk
          retention-days: 7
